---

- name: Install required tools by Consul
  apt: name={{ item }}
  with_items:
    - unzip

- name: Create directory structure for Consul
  file:
    name: "{{ item }}"
    owner: root
    group: root
    state: directory
    recurse: yes
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_install_dir }}"
    - "{{ consul_log_dir }}"

- name: Install Consul
  unarchive:
    src: "{{ consul_download_url }}"
    dest: "{{ consul_install_dir }}"
    remote_src: True
    mode: 0755
    creates: "{{ consul_install_dir }}/consul"

- name: Create Upstart config for Consul
  template:
    src: upstart/consul.conf.j2
    dest: /etc/init/consul.conf
    mode: 0644
  notify:
    - restart consul
