---

- name: Create Upstart config for Cabify App
  template:
    src: upstart/cabify.conf.j2
    dest: /etc/init/cabify.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart cabify
