---

- name: Install Python PIP (Python Package Installer)
  apt:
    name: python-pip
    state: present

- name: Install Bottle Web Framework with PIP
  pip:
    name: bottle
    version: "{{ cabify_bottle_version }}"
    state: present

- name: Deploy example Cabify App
  copy:
    src: .
    dest: "{{ cabify_path }}"
    owner: root
    group: root
  notify:
    - restart cabify
